# -*- coding: utf-8 -*-
"""rulers_dress_standardized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182MHPwaL0v0N-Icfs4LR9CYiS3V3hoZ8
"""

# -*- coding: utf-8 -*-
"""
RULERS Framework - Standardized Implementation for DREsS Dataset

This script implements the RULERS framework adapted for DREsS (Medical/Technical):
1. Phase I: Rubric Compilation (Natural Language -> Locked Checklist)
2. Phase II: Evidence-Anchored Scoring (Checklist Execution + Verbatim Evidence)
3. Calibration: WGR (Wasserstein Generative Regression)
"""

import os
import json
import argparse
import hashlib
import time
import numpy as np
from typing import List, Dict, Any
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge
from scipy import interpolate
from openai import OpenAI

# ======================================================
# SECTION 1: PROMPT TEMPLATES (Unified Strategy)
# ======================================================
PROMPT_TEMPLATE_PHASE_1 = """You are an expert evaluator. Your job is to compile
the OFFICIAL rubric below into a FIXED analytic
rubric bundle for the {DATASET_NAME} dataset.

Input Context:
- Raw Rubric: {RAW_RUBRIC_TEXT}
- Calibration Anchors: {FEW_SHOT_EXAMPLES}

Your Constraints:
1. Define EXACTLY {N} traits:
   {FIXED_TRAIT_LIST}
   (e.g., Content, Organization...)
2. Create EXACTLY {M} checklist checkpoints total:
   - Scale: 0=not present, 1=partially, 2=clearly.
   - Items must be auditable from verbatim evidence.
3. Hard Constraints:
   - Must COVER all official key concepts.
   - evidence_rules.min_evidence must be {MIN_EV}.
   - Do not invent new scoring systems; remain
     faithful to the official guidelines.

Output Format:
- Return a structured JSON Object containing the
  taxonomy, checklist items (C01..C{M}), and rules.
- This output will be hashed and locked.
"""

PROMPT_TEMPLATE_PHASE_2 = """You are a judge scoring {INPUT_TYPE} using a LOCKED
rubric bundle (hash must match). Return JSON only.

LOCKED BUNDLE HASH: {BUNDLE_HASH}

Input Data:
- Sentence Bank (ID -> Text): {SENTENCE_BANK}
- Locked Criteria: {LOCKED_TRAITS_JSON}
- Locked Checklist: {LOCKED_CHECKLIST_JSON}

Your Task:
1. Checklist Execution:
   - Rate ALL {M} items exactly once in {{0, 1, 2}}.
   - Decision=2 requires explicit positive evidence.

2. Evidence Extraction (Critical):
   - For EACH trait, extract EXACTLY {MIN_EV} quotes.
   - Source: Quotes must be VERBATIM substrings
     from the provided Sentence Bank.
   - Anchor: You must cite the specific sent_id.

3. Boundary Justification:
   - For each trait, provide a compact boundary check:
     "Why not +1 score AND why not -1 score?"

4. Anti-Halo Constraint:
   - Do NOT output identical scores across all traits
     unless strictly warranted by evidence.
   - Avoid central tendency bias.

Return the structured evaluation object now.
"""

# ======================================================
# SECTION 2: UTILS & CONFIG
# ======================================================
def get_client(api_key: str):
    return OpenAI(api_key=api_key)

def calculate_hash(data: Any) -> str:
    s = json.dumps(data, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(s.encode('utf-8')).hexdigest()[:16]

def split_sentences(text: str) -> List[Dict[str, Any]]:
    # DREsS essays are standard text
    raw_sents = [s.strip() for s in text.replace('\n', '.').split('.') if s.strip()]
    return [{"sent_id": i, "text": s} for i, s in enumerate(raw_sents)]

# ======================================================
# SECTION 3: CORE CLASSES
# ======================================================

class RubricCompiler:
    def __init__(self, model: str, client: OpenAI):
        self.model = model
        self.client = client

    def compile(self, raw_rubric: str, traits: List[str], checklist_n: int, min_ev: int) -> Dict[str, Any]:
        prompt = PROMPT_TEMPLATE_PHASE_1.format(
            DATASET_NAME="DREsS-Medical",
            RAW_RUBRIC_TEXT=raw_rubric[:2000],
            FEW_SHOT_EXAMPLES="[Medical Essay Anchors]",
            N=len(traits),
            FIXED_TRAIT_LIST=", ".join(traits),
            M=checklist_n,
            MIN_EV=min_ev
        )
        print(f"[*] Compiling DREsS Rubric with {self.model}...")
        rubric_bundle = {
            "taxonomy": {t: "Description..." for t in traits},
            "checklist": [f"C{i:02d}" for i in range(1, checklist_n + 1)],
            "rules": {"min_evidence": min_ev},
            "metadata": {"compiled_at": time.time()}
        }
        rubric_bundle["hash"] = calculate_hash(rubric_bundle)
        return rubric_bundle

class EvidenceScorer:
    def __init__(self, model: str, client: OpenAI):
        self.model = model
        self.client = client

    def score(self, text: str, locked_bundle: Dict[str, Any]) -> Dict[str, Any]:
        sentence_bank = split_sentences(text)

        prompt = PROMPT_TEMPLATE_PHASE_2.format(
            INPUT_TYPE="Medical Essay",
            BUNDLE_HASH=locked_bundle["hash"],
            SENTENCE_BANK=json.dumps(sentence_bank[:5], indent=2),
            LOCKED_TRAITS_JSON=json.dumps(locked_bundle["taxonomy"]),
            LOCKED_CHECKLIST_JSON=json.dumps(locked_bundle["checklist"]),
            M=len(locked_bundle["checklist"]),
            MIN_EV=locked_bundle["rules"]["min_evidence"]
        )

        return {
            "scores": {k: 4.0 for k in locked_bundle["taxonomy"].keys()}, # DREsS uses floats often
            "checklist_decisions": [0] * len(locked_bundle["checklist"]),
            "evidence_quotes": [],
            "boundary_justification": "Simulated DREsS analysis."
        }

class CalibrationEngine:
    """Standard WGR Implementation."""
    def __init__(self, ridge_alpha: float):
        self.pipeline = Pipeline([
            ("poly", PolynomialFeatures(degree=2, include_bias=False)),
            ("scaler", StandardScaler()),
            ("regressor", Ridge(alpha=ridge_alpha))
        ])
        self.mapper = None

    def fit(self, X_features: np.ndarray, y_human: np.ndarray):
        self.pipeline.fit(X_features, y_human)
        y_pred = self.pipeline.predict(X_features)
        self.mapper = interpolate.interp1d(
            np.sort(y_pred),
            np.sort(y_human),
            kind='linear',
            fill_value="extrapolate"
        )

    def predict(self, X_features: np.ndarray) -> np.ndarray:
        raw_pred = self.pipeline.predict(X_features)
        if self.mapper:
            return self.mapper(raw_pred)
        return raw_pred

# ======================================================
# SECTION 4: MAIN EXECUTION
# ======================================================
def main():
    parser = argparse.ArgumentParser(description="RULERS: DREsS Standardized Pipeline")
    parser.add_argument("--data_path", type=str, required=True, help="Path to input TSV/CSV")
    parser.add_argument("--api_key", type=str, default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", type=str, default="gpt-4o")

    # [SENSITIVE PARAMETER] DREsS default checklist size
    parser.add_argument("--checklist_n", type=int, default=18, help="Number of checklist items (M)")

    # [SENSITIVE PARAMETER] Evidence count
    parser.add_argument("--min_ev", type=int, default=2, help="Minimum evidence per trait")

    # [SENSITIVE PARAMETER] WGR
    parser.add_argument("--wgr_alpha", type=float, default=0.5, help="Ridge regression alpha")

    args = parser.parse_args()

    client = get_client(args.api_key)
    compiler = RubricCompiler(args.model, client)
    scorer = EvidenceScorer(args.model, client)
    calibrator = CalibrationEngine(args.wgr_alpha)

    # DREsS Traits
    traits = ["Content", "Organization", "Language"]
    raw_rubric = "Insert Official DREsS Rubric Here..."

    locked_bundle = compiler.compile(raw_rubric, traits, args.checklist_n, args.min_ev)
    print(f"[*] Bundle Locked. Hash: {locked_bundle['hash']}")

    print("[*] Phase II Scoring started...")
    # Simulated data (DREsS uses floats usually, e.g., 3.5)
    X_sim = np.random.rand(80, 5)
    y_sim = np.random.choice([2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0], 80)

    print(f"[*] Fitting WGR with alpha={args.wgr_alpha}...")
    calibrator.fit(X_sim, y_sim)
    print("[*] Calibration complete.")

if __name__ == "__main__":
    main()