# -*- coding: utf-8 -*-
"""run_autoscore_universal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mob2cASbhUsrSK_AWq8AebkuXegfdugy
"""

# -*- coding: utf-8 -*-
"""
Universal AutoScore Baseline
----------------------------
A fully generalized Two-Stage (Extraction -> Scoring) pipeline for any text evaluation task.

This script decouples the dataset specifics from the scoring logic.
It normalizes inputs into a standard schema and applies a configurable scoring pipeline.

Pipeline:
  1. Extraction Phase: LLM extracts rubric-relevant details (Evidence/Z).
  2. Scoring Phase: LLM assigns a score based on Evidence + Rubric.
  3. Calibration Phase: Isotonic Regression maps raw LLM scores to human distribution.

Usage:
  python run_autoscore_universal.py --preset ASAP --openai_key "..."
  python run_autoscore_universal.py --data_path data.csv --rubric_text "..." --min_score 1 --max_score 5
"""

import os
import re
import time
import json
import argparse
import threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple, Any
from sklearn.metrics import cohen_kappa_score
from sklearn.isotonic import IsotonicRegression

# ==========================================
# 1. Configuration System
# ==========================================

@dataclass
class TaskConfig:
    name: str
    rubric_text: str
    min_score: float
    max_score: float
    step_size: float        # e.g., 1.0 for integers, 0.5 for DREsS
    cols_text: List[str]    # Columns to merge as input (e.g. ['prompt', 'essay'])
    col_label: str          # Column for human labels
    col_id: str             # Column for IDs
    sys_msg: str = "You are an AI evaluator."

# Built-in Presets for your specific datasets
PRESETS = {
    "ASAP": TaskConfig(
        name="ASAP",
        rubric_text="SCORE 1-6. 6: Mastery. 5: Reasonable. 4: Adequate. 3: Developing. 2: Little. 1: Very Little.",
        min_score=1, max_score=6, step_size=1.0,
        cols_text=["prompt_text", "essay"], col_label="score", col_id="essay_id",
        sys_msg="You are an automated essay scoring judge."
    ),
    "SUMM": TaskConfig(
        name="SUMM",
        rubric_text="Score Overall Quality (1-7). 7: Excellent. 4: Okay. 1: Terrible. Check for hallucinations.",
        min_score=1, max_score=7, step_size=1.0,
        cols_text=["info.title", "info.post", "summary.text"], col_label="summary.axes.overall", col_id="info.id",
        sys_msg="You are a summarization evaluator."
    ),
    "DRESS": TaskConfig(
        name="DRESS",
        rubric_text="Score Content, Org, Lang (1-5 each). OUTPUT TOTAL SUM (3.0-15.0).",
        min_score=3.0, max_score=15.0, step_size=0.5,
        cols_text=["prompt", "essay"], col_label="total", col_id="id",
        sys_msg="You are a rubric-aware extraction and scoring agent."
    )
}

# ==========================================
# 2. Universal Data Loader
# ==========================================

def smart_load(path: str) -> pd.DataFrame:
    """Detects file format and loads data."""
    if path.endswith(".parquet"): return pd.read_parquet(path)
    if path.endswith(".tsv"): return pd.read_csv(path, sep='\t', encoding='latin1')
    try: return pd.read_csv(path, encoding='utf-8')
    except: return pd.read_csv(path, encoding='latin1')

def normalize_data(df: pd.DataFrame, config: TaskConfig) -> pd.DataFrame:
    """Normalizes any dataframe into [id, input_text, human_label]."""

    # 1. Flatten nested columns (basic support for 'col.subcol')
    for col in config.cols_text + [config.col_label, config.col_id]:
        if "." in col and col not in df.columns:
            parts = col.split(".")
            if parts[0] in df.columns:
                # One level deep
                df[col] = df[parts[0]].apply(lambda x: x.get(parts[1]) if isinstance(x, dict) else np.nan)
                # Two levels deep (e.g. summary.axes.overall)
                if len(parts) > 2:
                    df[col] = df[col].apply(lambda x: x.get(parts[2]) if isinstance(x, dict) else np.nan)

    # 2. Merge Text Columns
    def merge_text(row):
        parts = []
        for c in config.cols_text:
            val = str(row.get(c, "")).strip()
            if val: parts.append(f"[{c.upper()}]:\n{val}")
        return "\n\n".join(parts)

    out_df = pd.DataFrame()

    # ID
    if config.col_id in df.columns:
        out_df["id"] = df[config.col_id].astype(str)
    else:
        out_df["id"] = range(len(df))

    # Text
    out_df["input_text"] = df.apply(merge_text, axis=1)

    # Label (Handle DREsS Summation Fallback if 'total' missing)
    if config.name == "DRESS" and config.col_label not in df.columns:
        sub_cols = ['content', 'organization', 'language']
        if all(c in df.columns for c in sub_cols):
            out_df["human_label"] = df[sub_cols].sum(axis=1)
    else:
        out_df["human_label"] = pd.to_numeric(df[config.col_label], errors='coerce')

    return out_df.dropna(subset=["input_text", "human_label"])

# ==========================================
# 3. LLM Client & Scorer
# ==========================================

@dataclass
class UsageStats:
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost: float = 0.0
    lock: threading.Lock = field(default_factory=threading.Lock)

    def update(self, pt, ct):
        with self.lock:
            self.prompt_tokens += pt
            self.completion_tokens += ct
            # Approx cost (GPT-4o-mini)
            self.cost += (pt * 0.15 + ct * 0.60) / 1e6

def call_llm(model, messages, api_key, max_tokens=500):
    from openai import OpenAI
    client = OpenAI(api_key=api_key)
    try:
        resp = client.chat.completions.create(
            model=model, messages=messages, max_tokens=max_tokens, temperature=0.0,
            response_format={"type": "json_object"}
        )
        return resp.choices[0].message.content, resp.usage.prompt_tokens, resp.usage.completion_tokens
    except Exception as e:
        print(f"LLM Error: {e}")
        return "{}", 0, 0

def process_row_autoscore(row, config: TaskConfig, model: str, api_key: str, usage: UsageStats):
    """
    The Two-Stage Pipeline:
    1. Extraction: Get 'Z' (Evidence).
    2. Scoring: Get Score based on Z.
    """

    # --- Stage 1: Extraction ---
    sys_msg_1 = f"{config.sys_msg} Phase 1: Extraction."
    user_msg_1 = f"""
[Input Data]
{row['input_text'][:10000]}

[Rubric]
{config.rubric_text}

Task: Extract key evidence, strengths, and weaknesses relevant to the rubric.
Output strict JSON with keys: "evidence", "strengths", "weaknesses".
"""
    txt1, pt1, ct1 = call_llm(model, [{"role":"system","content":sys_msg_1}, {"role":"user","content":user_msg_1}], api_key, max_tokens=800)
    usage.update(pt1, ct1)

    # --- Stage 2: Scoring ---
    sys_msg_2 = f"{config.sys_msg} Phase 2: Scoring."
    user_msg_2 = f"""
[Rubric]
{config.rubric_text}

[Extracted Evidence]
{txt1}

[Original Input]
{row['input_text'][:4000]}

Task: Assign a score between {config.min_score} and {config.max_score}.
Output strict JSON: {{"score": <number>, "reason": "..."}}
"""
    txt2, pt2, ct2 = call_llm(model, [{"role":"system","content":sys_msg_2}, {"role":"user","content":user_msg_2}], api_key, max_tokens=300)
    usage.update(pt2, ct2)

    # --- Parsing ---
    try:
        data = json.loads(txt2)
        raw = float(data.get("score", -1))
    except:
        # Regex Fallback
        m = re.search(r'score":\s*([\d\.]+)', txt2)
        raw = float(m.group(1)) if m else -1.0

    # Clamp
    if raw != -1:
        raw = max(config.min_score, min(config.max_score, raw))

    return {
        "id": row['id'],
        "human": row['human_label'],
        "raw_pred": raw,
        "extraction": txt1,
        "reason": data.get("reason", "") if raw != -1 else ""
    }

# ==========================================
# 4. Calibration & Metrics
# ==========================================

def run_calibration_pipeline(train_rows, test_rows, config):
    # 1. Prepare Data
    X_train = [r['raw_pred'] for r in train_rows if r['raw_pred'] != -1]
    y_train = [r['human'] for r in train_rows if r['raw_pred'] != -1]

    if len(X_train) < 5:
        print("Warning: Not enough valid calibration data.")
        iso = None
    else:
        # 2. Fit Isotonic
        iso = IsotonicRegression(y_min=config.min_score, y_max=config.max_score, out_of_bounds="clip")
        iso.fit(X_train, y_train)

    # 3. Predict & Round
    final_preds = []
    for r in test_rows:
        val = r['raw_pred']
        if val == -1:
            final_preds.append(config.min_score)
            continue

        # Apply Calibration
        if iso:
            val = iso.predict([val])[0]

        # Universal Rounding (Step Size)
        # e.g., 3.3 -> step 0.5 -> 3.3/0.5=6.6 -> 7 -> 7*0.5=3.5
        val = round(val / config.step_size) * config.step_size
        final_preds.append(val)

    return final_preds

# ==========================================
# 5. Main Execution
# ==========================================

def main():
    parser = argparse.ArgumentParser(description="Universal AutoScore Runner")
    parser.add_argument("--preset", choices=PRESETS.keys(), help="Use built-in dataset config")
    parser.add_argument("--data_path", required=True, help="Path to data file")
    parser.add_argument("--test_path", help="Optional separate test file")

    # Overrides
    parser.add_argument("--rubric_text", help="Custom rubric text")
    parser.add_argument("--min_score", type=float)
    parser.add_argument("--max_score", type=float)
    parser.add_argument("--step_size", type=float, default=1.0)
    parser.add_argument("--cols_text", help="Columns to merge (comma-separated)")
    parser.add_argument("--col_label", help="Label column")

    # Runtime
    parser.add_argument("--openai_key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--calib_n", type=int, default=100)
    parser.add_argument("--max_test", type=int, default=500)
    parser.add_argument("--parallel", type=int, default=8)
    parser.add_argument("--out_dir", default="results_autoscore_universal")

    args = parser.parse_args()

    # 1. Config Setup
    if args.preset:
        cfg = PRESETS[args.preset]
    else:
        cfg = TaskConfig("CUSTOM", "", 1, 5, 1, ["text"], "label", "id")

    if args.rubric_text: cfg.rubric_text = args.rubric_text
    if args.min_score: cfg.min_score = args.min_score
    if args.max_score: cfg.max_score = args.max_score
    if args.step_size: cfg.step_size = args.step_size
    if args.cols_text: cfg.cols_text = args.cols_text.split(",")
    if args.col_label: cfg.col_label = args.col_label

    print(f"--- Universal AutoScore: {cfg.name} ---")
    print(f"Schema: {cfg.cols_text} -> Input | Label: {cfg.col_label}")

    # 2. Data Loading
    full_df = smart_load(args.data_path)
    full_std = normalize_data(full_df, cfg)

    if args.test_path:
        test_raw = smart_load(args.test_path)
        test_std = normalize_data(test_raw, cfg)
        train_std = full_std
    else:
        train_std = full_std.iloc[:args.calib_n]
        test_std = full_std.iloc[args.calib_n:]

    train_std = train_std.head(args.calib_n)
    test_std = test_std.head(args.max_test)

    print(f"Calib N: {len(train_std)} | Test N: {len(test_std)}")
    os.makedirs(args.out_dir, exist_ok=True)
    usage = UsageStats()

    # 3. Execution Helper
    def run_batch(df, desc):
        results = []
        with ThreadPoolExecutor(max_workers=args.parallel) as ex:
            futs = [ex.submit(process_row_autoscore, row, cfg, args.model, args.openai_key, usage) for _, row in df.iterrows()]
            for f in as_completed(futs):
                results.append(f.result())
            print(f"Finished {desc}")
        return results

    # Run Phases
    calib_res = run_batch(train_std, "Calibration Phase")
    test_res = run_batch(test_std, "Test Phase")

    # 4. Calibration & Prediction
    final_preds = run_calibration_pipeline(calib_res, test_res, cfg)

    # 5. Metrics
    y_true = [r['human'] for r in test_res]

    # QWK Handling (Integer mapping via step_size)
    factor = int(1 / cfg.step_size)
    yt_int = np.round(np.array(y_true) * factor).astype(int)
    yp_int = np.round(np.array(final_preds) * factor).astype(int)

    qwk = cohen_kappa_score(yt_int, yp_int, weights="quadratic")

    # Save
    df_out = pd.DataFrame(test_res)
    df_out['final_pred'] = final_preds
    df_out.to_csv(os.path.join(args.out_dir, "predictions.csv"), index=False)

    print("\n" + "="*40)
    print(f"RESULTS ({cfg.name})")
    print(f"QWK Score: {qwk:.4f}")
    print(f"Est. Cost: ${usage.cost:.4f}")
    print("="*40)

if __name__ == "__main__":
    main()