# -*- coding: utf-8 -*-
"""run_mts_universal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zG7hw2xfeiBDSvtQv5mgH1YvCJBniqNY
"""

# -*- coding: utf-8 -*-
"""
Universal MTS (Multi-Trait Scoring) - Evidence-First Only
---------------------------------------------------------
A generalized scoring pipeline that enforces a 2-step "Evidence-First" protocol for robustness.

Pipeline:
1. Decompose: For N user-defined traits:
   - Call 1 (Analysis): Extract specific strengths & weaknesses (Evidence).
   - Call 2 (Scoring): Assign fine-grained scores based on that evidence.
2. Aggregate: Combine trait scores into a raw metric (Mean or Sum).
3. Calibrate: Map raw metric to human distribution via Isotonic Regression.

Usage:
  python run_mts_universal.py --data_path data.csv --traits "Logic,Style" --aggregator MEAN
"""

import os
import re
import time
import json
import argparse
import threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from sklearn.metrics import cohen_kappa_score
from sklearn.isotonic import IsotonicRegression

# ==========================================
# 1. Configuration
# ==========================================

@dataclass
class MTSConfig:
    traits: List[str]       # e.g. ["Coherence", "Accuracy"]
    aggregator: str         # "MEAN" or "SUM"
    min_score: float        # e.g. 1
    max_score: float        # e.g. 6
    step_size: float        # e.g. 1.0 or 0.5
    cols_text: List[str]    # input columns to merge
    col_label: str          # label column
    col_id: str             # id column
    rubric_context: str = "" # Optional extra context

# ==========================================
# 2. Universal Data Loader
# ==========================================

def smart_load(path: str) -> pd.DataFrame:
    if path.endswith(".parquet"): return pd.read_parquet(path)
    if path.endswith(".tsv"): return pd.read_csv(path, sep='\t', encoding='latin1')
    try: return pd.read_csv(path, encoding='utf-8')
    except: return pd.read_csv(path, encoding='latin1')

def normalize_data(df: pd.DataFrame, config: MTSConfig) -> pd.DataFrame:
    """Normalizes input into [id, input_text, human_label]."""

    # Simple flatten for dot notation (e.g. summary.axes.overall)
    for col in config.cols_text + [config.col_label, config.col_id]:
        if "." in col and col not in df.columns:
            parts = col.split(".")
            if parts[0] in df.columns:
                df[col] = df[parts[0]].apply(lambda x: x.get(parts[1]) if isinstance(x, dict) else np.nan)
                if len(parts) > 2:
                    df[col] = df[col].apply(lambda x: x.get(parts[2]) if isinstance(x, dict) else np.nan)

    def merge_text(row):
        texts = []
        for c in config.cols_text:
            val = str(row.get(c, "")).strip()
            if val: texts.append(f"[{c.upper()}]:\n{val}")
        return "\n\n".join(texts)

    out_df = pd.DataFrame()

    # ID
    if config.col_id in df.columns:
        out_df["id"] = df[config.col_id].astype(str)
    else:
        out_df["id"] = range(len(df))

    # Text
    out_df["input_text"] = df.apply(merge_text, axis=1)

    # Label (Handle Summation Fallback if label col missing but traits exist)
    if config.col_label not in df.columns:
        # Check if column names match the traits (e.g. for DREsS)
        lower_cols = [c.lower() for c in df.columns]
        trait_cols_lower = [t.lower() for t in config.traits]
        if all(t in lower_cols for t in trait_cols_lower):
            # Sum them up
            out_df["human_label"] = df[trait_cols_lower].sum(axis=1)
        else:
             out_df["human_label"] = np.nan
    else:
        out_df["human_label"] = pd.to_numeric(df[config.col_label], errors='coerce')

    return out_df.dropna(subset=["input_text", "human_label"])

# ==========================================
# 3. LLM Client & Evidence-First Logic
# ==========================================

@dataclass
class UsageStats:
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost: float = 0.0
    lock: threading.Lock = field(default_factory=threading.Lock)

    def update(self, pt, ct):
        with self.lock:
            self.prompt_tokens += pt
            self.completion_tokens += ct
            self.cost += (pt * 0.15 + ct * 0.60) / 1e6

def call_llm(model, messages, api_key, max_tokens=500):
    from openai import OpenAI
    client = OpenAI(api_key=api_key)
    try:
        resp = client.chat.completions.create(
            model=model, messages=messages, max_tokens=max_tokens, temperature=0.0,
            response_format={"type": "json_object"}
        )
        return resp.choices[0].message.content, resp.usage.prompt_tokens, resp.usage.completion_tokens
    except Exception as e:
        print(f"LLM Error: {e}")
        return "{}", 0, 0

def score_row_evidence_first(row, config: MTSConfig, model: str, api_key: str, usage: UsageStats):
    """
    Strict 2-Step Protocol: Extract Evidence -> Assign Score.
    """
    input_text = row['input_text'][:12000] # Truncate safely
    traits_str = ", ".join(config.traits)

    # --- Step 1: Evidence Extraction ---
    sys_msg_1 = "You are an expert analyst. Your goal is to extract evidence for evaluation."
    user_msg_1 = f"""
[Input Data]
{input_text}

[Rubric Context]
{config.rubric_context}

Task: Analyze the input for the following traits: {traits_str}.
For EACH trait, identify 1-2 specific strengths and 1-2 specific weaknesses/errors based on the text.

Output JSON: {{ "{config.traits[0]}": "evidence string...", ... }}
"""
    txt1, pt1, ct1 = call_llm(model, [{"role":"system","content":sys_msg_1}, {"role":"user","content":user_msg_1}], api_key, max_tokens=800)
    usage.update(pt1, ct1)

    # --- Step 2: Scoring based on Evidence ---
    sys_msg_2 = "You are an expert scorer. Assign numeric scores based on the analyzed evidence."

    # We ask for a fine-grained 0-10 scale internally for precision, then aggregate.
    # Calibration will map this internal scale to the target human scale.
    user_msg_2 = f"""
[Input Data]
{input_text}

[Evidence Analysis]
{txt1}

Task: Evaluate the text on the following traits: {traits_str}.
Based strictly on the evidence identified above, assign a score from 0 (Poor) to 10 (Perfect) for EACH trait.

Output JSON: {{ "{config.traits[0]}": <0-10>, ... }}
"""

    msgs = [{"role":"system","content":sys_msg_2}, {"role":"user","content":user_msg_2}]
    txt2, pt2, ct2 = call_llm(model, msgs, api_key, max_tokens=300)
    usage.update(pt2, ct2)

    # Parse Scores
    try:
        data = json.loads(txt2)
    except:
        data = {}

    trait_scores = []
    for t in config.traits:
        # Robust retrieval (fuzzy match fallback)
        val = data.get(t)
        if val is None:
            for k in data.keys():
                if t.lower() in k.lower(): val = data[k]; break

        try:
            val = float(val)
        except:
            val = 5.0 # Default mid-point

        trait_scores.append(val)

    # Aggregate (Mean or Sum of the 0-10 scores)
    if config.aggregator == "MEAN":
        raw_metric = np.mean(trait_scores)
    elif config.aggregator == "SUM":
        raw_metric = np.sum(trait_scores)
    else:
        raw_metric = np.mean(trait_scores)

    return {
        "id": row['id'],
        "human": row['human_label'],
        "raw_metric": raw_metric,
        "trait_scores": trait_scores,
        "evidence": txt1
    }

# ==========================================
# 4. Calibration & Metrics
# ==========================================

def run_calibration(train_res: List[Dict], test_res: List[Dict], config: MTSConfig):
    # 1. Prepare Calibration Data
    X_train = [r['raw_metric'] for r in train_res]
    y_train = [r['human'] for r in train_res]

    if len(X_train) < 5:
        print("Warning: Not enough calibration data.")
        return [config.min_score] * len(test_res)

    # 2. Fit Isotonic Regression
    # Maps internal aggregated score (e.g. 0-10 mean or 0-30 sum) to Human Target Range
    iso = IsotonicRegression(y_min=config.min_score, y_max=config.max_score, out_of_bounds="clip")
    iso.fit(X_train, y_train)

    # 3. Predict & Round
    final_preds = []
    for r in test_res:
        val = iso.predict([r['raw_metric']])[0]

        # Universal Rounding
        val = round(val / config.step_size) * config.step_size
        final_preds.append(val)

    return final_preds

# ==========================================
# 5. Main Execution
# ==========================================

def main():
    parser = argparse.ArgumentParser(description="Universal MTS (Evidence-First) Runner")

    # Input Data
    parser.add_argument("--data_path", required=True, help="Main data file")
    parser.add_argument("--test_path", help="Optional test file")
    parser.add_argument("--cols_text", default="text", help="Text column(s) to merge (comma-sep)")
    parser.add_argument("--col_label", default="label", help="Label column")
    parser.add_argument("--col_id", default="id", help="ID column")

    # MTS Configuration
    parser.add_argument("--traits", required=True, help="Comma-separated traits (e.g. 'Logic,Style')")
    parser.add_argument("--aggregator", choices=["MEAN", "SUM"], default="MEAN")

    # Target Scale
    parser.add_argument("--min_score", type=float, default=1)
    parser.add_argument("--max_score", type=float, default=6)
    parser.add_argument("--step_size", type=float, default=1.0)

    # Runtime
    parser.add_argument("--openai_key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--calib_n", type=int, default=100)
    parser.add_argument("--max_test", type=int, default=500)
    parser.add_argument("--parallel", type=int, default=8)
    parser.add_argument("--out_dir", default="results_mts_universal")

    args = parser.parse_args()

    # 1. Setup Config
    traits_list = [t.strip() for t in args.traits.split(",")]
    cols_text_list = [c.strip() for c in args.cols_text.split(",")]

    cfg = MTSConfig(
        traits=traits_list,
        aggregator=args.aggregator,
        min_score=args.min_score,
        max_score=args.max_score,
        step_size=args.step_size,
        cols_text=cols_text_list,
        col_label=args.col_label,
        col_id=args.col_id
    )

    print(f"--- Universal MTS (Evidence-First) ---")
    print(f"Traits: {cfg.traits}")
    print(f"Aggregator: {cfg.aggregator}")
    print(f"Target: [{cfg.min_score}, {cfg.max_score}] (Step {cfg.step_size})")

    # 2. Load Data
    full_df = smart_load(args.data_path)
    full_std = normalize_data(full_df, cfg)

    if args.test_path:
        test_raw = smart_load(args.test_path)
        test_std = normalize_data(test_raw, cfg)
        train_std = full_std
    else:
        train_std = full_std.iloc[:args.calib_n]
        test_std = full_std.iloc[args.calib_n:]

    train_std = train_std.head(args.calib_n)
    test_std = test_std.head(args.max_test)

    print(f"Train N: {len(train_std)} | Test N: {len(test_std)}")
    os.makedirs(args.out_dir, exist_ok=True)
    usage = UsageStats()

    # 3. Execution Helper
    def run_batch(df, desc):
        results = []
        with ThreadPoolExecutor(max_workers=args.parallel) as ex:
            futs = [ex.submit(score_row_evidence_first, row, cfg, args.model, args.openai_key, usage) for _, row in df.iterrows()]
            for f in as_completed(futs):
                results.append(f.result())
            print(f"Finished {desc}")
        return results

    # Run
    calib_res = run_batch(train_std, "Calibration")
    test_res = run_batch(test_std, "Testing")

    # 4. Calibration & Predict
    final_preds = run_calibration(calib_res, test_res, cfg)

    # 5. Metrics
    y_true = [r['human'] for r in test_res]

    # QWK Map
    factor = int(1 / cfg.step_size)
    yt_int = np.round(np.array(y_true) * factor).astype(int)
    yp_int = np.round(np.array(final_preds) * factor).astype(int)

    qwk = cohen_kappa_score(yt_int, yp_int, weights="quadratic")

    # Save
    out_df = pd.DataFrame(test_res)
    out_df['final_pred'] = final_preds
    out_df.to_csv(os.path.join(args.out_dir, "predictions.csv"), index=False)

    print("\n" + "="*40)
    print(f"MTS RESULTS")
    print(f"QWK Score: {qwk:.4f}")
    print(f"Est. Cost: ${usage.cost:.4f}")
    print("="*40)

if __name__ == "__main__":
    main()