# -*- coding: utf-8 -*-
"""run_dhs_universal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bAeFtGmtEgohCRMMK1pXoxYLomwPJwB
"""

# -*- coding: utf-8 -*-
"""
Universal DHS (Direct Holistic Scoring) Baseline
------------------------------------------------
A completely generalized pipeline for LLM-as-a-Judge tasks.
This script normalizes any text scoring task into a standard flow:
   Input(Text) + Rubric -> LLM -> Raw Score -> Calibration -> Final Score

Features:
- Dataset Agnostic: Handles any CSV/TSV/Parquet via column mapping.
- Logic Agnostic: No dataset-specific branches in the main loop.
- Input Fusion: Automatically merges 'Prompt' and 'Response' columns if needed.
- Configurable: Score ranges, step sizes (int vs float), and rubrics are parameters.

Usage:
  python run_dhs_universal.py --preset ASAP --openai_key "..."
  python run_dhs_universal.py --data_path data.csv --rubric_path r.txt --min_score 1 --max_score 5
"""

import os
import re
import time
import json
import argparse
import random
import threading
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from typing import List, Dict, Optional, Tuple, Union
from sklearn.metrics import cohen_kappa_score
from sklearn.isotonic import IsotonicRegression

# ==========================================
# 1. Configuration & Presets
# ==========================================

@dataclass
class TaskConfig:
    name: str
    rubric_text: str
    min_score: float
    max_score: float
    step_size: float  # 1.0 for integers, 0.5 for DREsS, etc.
    cols_text: List[str]  # Columns to join as input (e.g. ['prompt', 'essay'])
    col_label: str        # Column containing human labels
    col_id: str           # ID column

# Built-in presets for convenience (optional usage)
PRESETS = {
    "ASAP": TaskConfig(
        name="ASAP",
        rubric_text="SCORE 1-6. 6: Clear mastery. 5: Reasonably consistent. 4: Adequate. 3: Developing. 2: Little mastery. 1: Very little mastery.",
        min_score=1, max_score=6, step_size=1.0,
        cols_text=["prompt_text", "essay"], col_label="score", col_id="essay_id"
    ),
    "SUMM": TaskConfig(
        name="SUMM",
        rubric_text="Score Overall Quality (1-7). 7: Excellent, accurate. 4: Okay. 1: Terrible, hallucinated.",
        min_score=1, max_score=7, step_size=1.0,
        cols_text=["info.title", "info.post", "summary.text"], col_label="summary.axes.overall", col_id="info.id"
    ),
    "DRESS": TaskConfig(
        name="DRESS",
        rubric_text="Score Content, Organization, Language (1-5 each). OUTPUT TOTAL SUM (3.0-15.0).",
        min_score=3.0, max_score=15.0, step_size=0.5,
        cols_text=["prompt", "essay"], col_label="total", col_id="id"
    )
}

# ==========================================
# 2. Universal Data Loader
# ==========================================

def smart_load(path: str) -> pd.DataFrame:
    """Auto-detects format and loads DataFrame."""
    if path.endswith(".parquet"): return pd.read_parquet(path)
    if path.endswith(".tsv"): return pd.read_csv(path, sep='\t', encoding='latin1')
    try: return pd.read_csv(path, encoding='utf-8')
    except: return pd.read_csv(path, encoding='latin1')

def normalize_data(df: pd.DataFrame, config: TaskConfig) -> pd.DataFrame:
    """
    Normalizes any dataframe into a standard schema:
    [id, input_text, human_label]
    """
    # 1. Flatten if necessary (for nested json/parquet cols like in SummHF)
    # Simple flatten for 'dot' notation columns if they don't exist
    for col in config.cols_text + [config.col_label, config.col_id]:
        if "." in col and col not in df.columns:
            # Very basic flattening support
            parts = col.split(".")
            if parts[0] in df.columns:
                df[col] = df[parts[0]].apply(lambda x: x.get(parts[1], {}) if isinstance(x, dict) else np.nan)
                if len(parts) > 2: # support deeper nesting like summary.axes.overall
                     df[col] = df[col].apply(lambda x: x.get(parts[2], np.nan) if isinstance(x, dict) else np.nan)

    # 2. Construct Input Text (Merge multiple columns)
    def merge_text(row):
        texts = []
        for c in config.cols_text:
            val = str(row.get(c, "")).strip()
            if val: texts.append(f"[{c.upper()}]:\n{val}")
        return "\n\n".join(texts)

    # 3. Create Standard DF
    out_df = pd.DataFrame()

    # Auto-detect ID if missing
    if config.col_id not in df.columns:
        out_df["id"] = range(len(df))
    else:
        out_df["id"] = df[config.col_id].astype(str)

    out_df["input_text"] = df.apply(merge_text, axis=1)

    # Handle Labels (Summation logic for DREsS handled here if 'total' missing)
    if config.col_label not in df.columns and config.name == "DRESS":
        # Fallback for DREsS if total column missing
        cols = ['content', 'organization', 'language']
        if all(c in df.columns for c in cols):
            out_df["human_label"] = df[cols].sum(axis=1)
    else:
        out_df["human_label"] = pd.to_numeric(df[config.col_label], errors='coerce')

    return out_df.dropna(subset=["input_text", "human_label"])

# ==========================================
# 3. Universal Scorer
# ==========================================

@dataclass
class UsageStats:
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost: float = 0.0
    lock: threading.Lock = threading.Lock()

    def update(self, pt, ct):
        with self.lock:
            self.prompt_tokens += pt
            self.completion_tokens += ct
            self.cost += (pt * 0.15 + ct * 0.60) / 1e6

def call_llm(model, messages, api_key, max_tokens=200):
    from openai import OpenAI
    client = OpenAI(api_key=api_key)
    try:
        resp = client.chat.completions.create(
            model=model, messages=messages, max_tokens=max_tokens, temperature=0.0,
            response_format={"type": "json_object"}
        )
        return resp.choices[0].message.content, resp.usage.prompt_tokens, resp.usage.completion_tokens
    except Exception as e:
        print(f"LLM Error: {e}")
        return "{}", 0, 0

def score_single_row(row, config: TaskConfig, model_name: str, api_key: str, usage: UsageStats):
    prompt = f"""
[Rubric]
{config.rubric_text}

[Input Data]
{row['input_text'][:12000]}

[Task]
Evaluate the Input Data based on the Rubric.
Assign a score between {config.min_score} and {config.max_score}.
Output strict JSON: {{"score": <number>, "reason": "<short justification>"}}
"""
    msgs = [{"role": "system", "content": "You are an expert evaluator."}, {"role": "user", "content": prompt}]

    txt, pt, ct = call_llm(model_name, msgs, api_key)
    usage.update(pt, ct)

    try:
        data = json.loads(txt)
        raw = float(data.get("score", -1))
    except:
        raw = -1.0

    # Clamp
    if raw != -1:
        raw = max(config.min_score, min(config.max_score, raw))

    return {
        "id": row['id'],
        "human": row['human_label'],
        "raw_pred": raw,
        "response": txt
    }

# ==========================================
# 4. Calibration & Metrics
# ==========================================

def run_calibration_and_predict(train_res: List[Dict], test_res: List[Dict], config: TaskConfig):
    # 1. Prepare Data
    X_train = [r['raw_pred'] for r in train_res if r['raw_pred'] != -1]
    y_train = [r['human'] for r in train_res if r['raw_pred'] != -1]

    if len(X_train) < 10:
        print("Warning: Not enough valid calibration data. Skipping calibration.")
        iso = None
    else:
        # 2. Fit Isotonic Regression
        iso = IsotonicRegression(y_min=config.min_score, y_max=config.max_score, out_of_bounds="clip")
        iso.fit(X_train, y_train)

    # 3. Predict & Round
    final_preds = []
    for r in test_res:
        val = r['raw_pred']
        if val == -1:
            final_preds.append(config.min_score)
            continue

        if iso:
            val = iso.predict([val])[0]

        # Universal Rounding Logic (Step Size)
        # e.g., if step=1 -> round(x); if step=0.5 -> round(x*2)/2
        val = round(val / config.step_size) * config.step_size
        final_preds.append(val)

    return final_preds

# ==========================================
# 5. Main Execution
# ==========================================

def main():
    parser = argparse.ArgumentParser(description="Universal DHS Runner")
    # Configuration sources
    parser.add_argument("--preset", choices=PRESETS.keys(), help="Load defaults for specific dataset")
    parser.add_argument("--rubric_path", help="Path to rubric text file (overrides preset)")
    parser.add_argument("--rubric_text", help="Inline rubric text (overrides preset)")

    # Data Paths
    parser.add_argument("--data_path", required=True, help="Main data file (train or full)")
    parser.add_argument("--test_path", help="Optional separate test file")

    # Generic Config Overrides (make it truly universal)
    parser.add_argument("--min_score", type=float)
    parser.add_argument("--max_score", type=float)
    parser.add_argument("--step_size", type=float, default=1.0)
    parser.add_argument("--cols_text", help="Comma-separated list of text columns")
    parser.add_argument("--col_label", help="Label column name")
    parser.add_argument("--col_id", help="ID column name")

    # Runtime
    parser.add_argument("--openai_key", default=os.getenv("OPENAI_API_KEY"))
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--calib_n", type=int, default=100)
    parser.add_argument("--max_test", type=int, default=500)
    parser.add_argument("--parallel", type=int, default=8)
    parser.add_argument("--out_dir", default="results_universal")

    args = parser.parse_args()

    # 1. Build Configuration Object
    if args.preset:
        cfg = PRESETS[args.preset]
    else:
        # Default fallback config
        cfg = TaskConfig("CUSTOM", "", 1, 5, 1, ["text"], "label", "id")

    # Override config with explicit args if provided
    if args.min_score: cfg.min_score = args.min_score
    if args.max_score: cfg.max_score = args.max_score
    if args.step_size: cfg.step_size = args.step_size
    if args.cols_text: cfg.cols_text = args.cols_text.split(",")
    if args.col_label: cfg.col_label = args.col_label
    if args.col_id: cfg.col_id = args.col_id

    # Load Rubric Text
    if args.rubric_path:
        with open(args.rubric_path, 'r', encoding='utf-8') as f: cfg.rubric_text = f.read()
    elif args.rubric_text:
        cfg.rubric_text = args.rubric_text

    print(f"--- Universal Run: {cfg.name} ---")
    print(f"Range: [{cfg.min_score}, {cfg.max_score}], Step: {cfg.step_size}")
    print(f"Input Cols: {cfg.cols_text} -> Merged")

    # 2. Load Data
    full_df = smart_load(args.data_path)
    full_std = normalize_data(full_df, cfg)

    if args.test_path:
        test_df_raw = smart_load(args.test_path)
        test_std = normalize_data(test_df_raw, cfg)
        train_std = full_std # Use data_path as train
    else:
        # Split single file
        train_std = full_std.iloc[:args.calib_n]
        test_std = full_std.iloc[args.calib_n:]

    # Subsample
    train_std = train_std.head(args.calib_n)
    test_std = test_std.head(args.max_test)

    print(f"Train N: {len(train_std)}, Test N: {len(test_std)}")
    os.makedirs(args.out_dir, exist_ok=True)
    usage = UsageStats()

    # 3. Execution Engine (Generic Loop)
    def run_batch(df, desc):
        results = []
        with ThreadPoolExecutor(max_workers=args.parallel) as ex:
            futs = [ex.submit(score_single_row, row, cfg, args.model, args.openai_key, usage) for _, row in df.iterrows()]
            for f in as_completed(futs):
                results.append(f.result())
            print(f"Finished {desc}")
        return results

    # Run Calibration Phase
    calib_res = run_batch(train_std, "Calibration Phase")

    # Run Test Phase
    test_res = run_batch(test_std, "Test Phase")

    # 4. Calibration & Prediction
    final_preds = run_calibration_and_predict(calib_res, test_res, cfg)

    # 5. Metrics & Saving
    y_true = [r['human'] for r in test_res]

    # QWK Handling: Map floats to integers via step size for QWK calculation
    # e.g. for step 0.5: 3.0->6, 3.5->7. This preserves ordinality perfectly.
    factor = int(1 / cfg.step_size)
    yt_int = np.round(np.array(y_true) * factor).astype(int)
    yp_int = np.round(np.array(final_preds) * factor).astype(int)

    qwk = cohen_kappa_score(yt_int, yp_int, weights="quadratic")

    # Save output
    out_df = pd.DataFrame(test_res)
    out_df['final_pred'] = final_preds
    out_df.to_csv(os.path.join(args.out_dir, "predictions.csv"), index=False)

    print("\n" + "="*40)
    print(f"RESULTS ({cfg.name})")
    print(f"QWK Score: {qwk:.4f}")
    print(f"Est. Cost: ${usage.cost:.4f}")
    print("="*40)

if __name__ == "__main__":
    main()